# Generated by Django 2.2.7 on 2019-11-24 20:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(default=1)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single room'), ('STANDARD', 'Double standard room'), ('TRIPLE', 'Triple room'), ('DELUX', 'Double room with kings bed')], default='STANDARD', max_length=1)),
                ('base_price', models.IntegerField(default=0)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.EmailField(max_length=254)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('pricesPerDay', jsonfield.fields.JSONField(default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_logic.Room')),
            ],
        ),
        migrations.CreateModel(
            name='PriceReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('price', models.IntegerField(default=0)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_logic.Reservation')),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='business_logic.Room')),
            ],
            options={
                'unique_together': {('date', 'room')},
            },
        ),
    ]
