# Generated by Django 3.0 on 2019-12-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceReservationDate',
            fields=[
                ('date', models.DateField(default='', primary_key=True, serialize=False)),
                ('price_1_0', models.IntegerField(default=100)),
                ('price_0_75', models.IntegerField(default=100)),
                ('price_0_5', models.IntegerField(default=100)),
                ('price_0_25', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('STATIC', 'Pokój o statyczna cena'), ('DYNAMIC', 'Pokój o dynamiczna cena')], default='STATIC', max_length=8)),
                ('base_price', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.EmailField(max_length=254)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_system.Room')),
            ],
        ),
    ]
