# Generated by Django 2.2.7 on 2019-11-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='BasePricePerNight',
            new_name='base_price_per_night',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='ImagePath',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='RoomId',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='RoomNumber',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='RoomType',
            new_name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='OptimalPricePerNightInCurrentWeek',
        ),
    ]
