//auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS= 'LOGIN_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS= 'LOGIN_SUCCESS';
export const REGISTER_USER_SUCCESS= 'REGISTER_USER_SUCCESS';

//Rooms

export const GET_ROOMS = 'GET_ROOMS';
export const DELETE_ROOM = 'DELETE_ROOM';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';


export const ADD_RESERVATION_SUCCESS = 'ADD_ROOM_SUCCESS';

export const GET_AVAILABLE_ROOMS = 'ADD_ROOM_SUCCESS';
